In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [3]:
vibration = np.array([2.1, 5.8, 3.4, 7.2, 1.8, 6.5, 4.1, 8.3, 2.6, 5.1, 3.9, 7.8, 1.5, 6.9, 4.6, 2.9, 8.7, 3.2, 5.5, 7.4, 2.3, 6.1, 4.4, 8.1, 1.9, 5.3, 3.7, 7.6, 2.8, 6.7, 4.9, 8.5, 1.6, 5.9, 3.1, 7.1, 2.4, 6.3, 4.2, 7.9])
temperature = np.array([42, 68, 51, 79, 38, 74, 58, 85, 45, 64, 55, 82, 35, 77, 61, 47, 88, 49, 66, 81, 41, 71, 59, 84, 39, 65, 53, 80, 46, 75, 63, 87, 36, 69, 48, 78, 43, 72, 56, 83])
hours = np.array([12.4, 38.6, 18.9, 45.2, 8.7, 41.3, 25.1, 52.8, 15.6, 34.9, 22.4, 48.7, 6.2, 43.5, 28.3, 16.8, 55.4, 19.7, 36.1, 47.9, 13.5, 39.8, 26.6, 51.2, 10.3, 35.7, 21.2, 46.4, 17.1, 42.6, 29.5, 54.1, 7.8, 37.4, 18.2, 44.8, 14.2, 40.5, 24.3, 49.6])
load = np.array([45, 82, 58, 91, 38, 87, 66, 95, 51, 78, 62, 93, 32, 89, 71, 54, 97, 56, 80, 92, 43, 85, 68, 94, 40, 79, 60, 90, 52, 88, 73, 96, 34, 83, 55, 90, 47, 86, 64, 92])
x_train = np.array([vibration, temperature, hours, load])
y_train = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

x_train = x_train.T

x_train.shape, y_train.shape

((40, 4), (40,))

In [32]:
scaler = StandardScaler()

new_xtrain = scaler.fit_transform(x_train)

scaler.mean_, scaler.scale_

(array([ 5.0025, 62.325 , 31.0825, 70.9   ]),
 array([ 2.19846395, 16.10494877, 14.72647085, 19.75322758]))

In [33]:
ld_rg = LogisticRegression()

ld_rg.fit(new_xtrain, y_train)

LogisticRegression()

In [39]:
print(f"Iterations ran for {ld_rg.n_iter_}")
ld_rg.coef_, ld_rg.intercept_

Iterations ran for [8]


(array([[0.95235411, 0.97639173, 1.09310197, 1.13805544]]),
 array([0.59804258]))

In [45]:
y_pred = ld_rg.predict(new_xtrain)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [48]:
ld_rg.score(new_xtrain, y_train)*100

100.0

In [54]:
x_data = np.array([[5.0, 62, 30.0, 70]] )
x_scaled_data = scaler.transform(x_data)

In [55]:
ld_rg.predict(x_scaled_data)

array([1])