In [1]:
import numpy as np

In [9]:
a = np.array([1., 2., 3.])
b = np.array([1, 2, 3])

print(a)

[1. 2. 3.]


In [10]:
a = np.zeros(5)

a

array([0., 0., 0., 0., 0.])

In [11]:
a = np.random.rand(5)
a

array([0.29255167, 0.95758674, 0.64684006, 0.59622539, 0.05033821])

In [17]:
a = np.arange(7)
np.shape(a)

(7,)

In [18]:
np.shape(b)

(3,)

In [19]:
a = np.arange(5)
b = -a
b

array([ 0, -1, -2, -3, -4])

In [20]:
b = a ** 2
b

array([ 0,  1,  4,  9, 16])

In [21]:
b = np.sum(a)
b

np.int64(10)

In [22]:
np.mean(a)

np.float64(2.0)

In [23]:
a = np.arange(5)
b = np.arange(5, 10)

In [24]:
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [28]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [29]:
c **= 2
c

array([ 25,  49,  81, 121, 169])

In [30]:
c = a ** b
c

array([     0,      1,    128,   6561, 262144])

In [31]:
d = np.array([1,2])
try:
    e = d+a
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (5,) 


In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a +b

array([5, 7, 9])

In [33]:
np.dot(a, b)

np.int64(32)

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(a)

(3, 3)

In [41]:
a = np.ones((2, 3, 4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [42]:
np.full((3, 7), 10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [47]:
a = np.arange(10)
a.reshape((2, 5, -1, 1))

array([[[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]]],


       [[[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]]])

In [62]:
a = np.arange(10)
a = a.reshape(5, 2)

In [64]:
a[3, 1]

np.int64(7)

In [67]:
a = np.arange(20)
a = a.reshape((2, -1))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [68]:
a[1, 2]

np.int64(12)

In [69]:
a[:, 2:7:2]

array([[ 2,  4,  6],
       [12, 14, 16]])

In [70]:
a[:, 2:7:2].shape

(2, 3)