In [1]:
import numpy as np

In [8]:
a = np.zeros((5, 3))
a[1:2]

array([[0., 0., 0.]])

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.sum()

np.int64(21)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.ndim

2

In [38]:
a = np.random.randint(0, 100, (6, 4))
print(a)
print(f"max of each column: {a.max(axis = 0)}")
print(f"mean of each row: {a.mean(axis = 1, keepdims = True)}")
print(f"index of the largest value in each column: {a.argmax(axis = 0)}")

[[44 62 51 11]
 [18 50 28 35]
 [ 9 40 92 82]
 [ 5 87  8 20]
 [19 52 75 68]
 [74 19  1 81]]
max of each column: [74 87 92 82]
mean of each row: [[42.  ]
 [32.75]
 [55.75]
 [30.  ]
 [53.5 ]
 [43.75]]
index of the largest value in each column: [5 3 2 2]


In [29]:
b = np.array()
print(b)

TypeError: array() missing required argument 'object' (pos 0)

In [27]:
arr = a[a > 50]
a[a > 50] = 50
a

array([[30, 50, 49, 50],
       [50, 21, 45,  5],
       [50, 50, 50, 45],
       [50, 50,  4, 50],
       [50, 50, 50, 50],
       [44, 50, 22, 24]], dtype=int32)

In [50]:
errors = np.random.randint(1, 41, (40))
x = np.random.randint(1, 100, (40, 3))

weighted_sum = errors @ x
print(weighted_sum)

new_weighted_sum = np.zeros(3)

for i in range(0, 3):
    new_weighted_sum[i] = (errors * x[:, i]).sum()

print(new_weighted_sum)

[36966 38112 37062]
[36966. 38112. 37062.]


In [62]:
v = np.array([4, 7, 1, 9, 3])
b = np.sort(v)[::-1]
c = np.argsort(v)[::-1]
print(b)
print(c)
#i don't know about the index one tell me

[9 7 4 3 1]
[3 1 0 4 2]
