In [2]:
import numpy as np

In [3]:
x = np.array([[952, 2, 1, 65],
              [1244, 3, 2, 64],
              [1947, 3, 2, 17],
              [1725, 3, 2, 42]])

In [4]:
mean = x.mean(axis = 0)
print(mean)
# before running the shape would be 4, 

[1467.      2.75    1.75   47.  ]


In [5]:
sigma = x.std(axis = 0)
print(sigma)

[391.1259388    0.4330127    0.4330127   19.60867155]


In [6]:
t = x - mean
print(f"x shape: {x.shape}, mean shape: {mean.shape}")
# since x shape is 4, 4 and mean shape is 4, 1 reading right from left it is ok for broadcasing , what is happegning is numpy is 
# virutally increasing the size of mean to match the size of x to perform operation
print(t)

x shape: (4, 4), mean shape: (4,)
[[-5.15e+02 -7.50e-01 -7.50e-01  1.80e+01]
 [-2.23e+02  2.50e-01  2.50e-01  1.70e+01]
 [ 4.80e+02  2.50e-01  2.50e-01 -3.00e+01]
 [ 2.58e+02  2.50e-01  2.50e-01 -5.00e+00]]


In [7]:
z = (x - mean)/sigma
print(f"mean for each column:{z.mean(axis = 0)}, standard deviation: {z.std(axis= 0)}")

mean for each column:[-2.77555756e-17  5.55111512e-17  5.55111512e-17 -1.38777878e-17], standard deviation: [1. 1. 1. 1.]


In [8]:
range_before = np.ptp(x, axis = 0)
range_after = np.ptp(z, axis = 0)
print(range_before, range_after)

[995   1   1  48] [2.54393765 2.30940108 2.30940108 2.44789658]


In [9]:
z

array([[-1.31671144, -1.73205081, -1.73205081,  0.91796122],
       [-0.57014884,  0.57735027,  0.57735027,  0.86696337],
       [ 1.2272262 ,  0.57735027,  0.57735027, -1.52993536],
       [ 0.65963408,  0.57735027,  0.57735027, -0.25498923]])

In [14]:
x = np.array([[952, 2, 1, 65],
              [1244, 3, 2, 64],
              [1947, 3, 2, 17],
              [1725, 3, 2, 42]])
mean = x.mean(axis=0)
sigma = x.std(axis=0)
z = (x - mean) / sigma

In [16]:
x_new = np.array([1200, 3, 1, 40])

z_new = (x_new - mean) / sigma
# my guess for the shape before running it is 4, 
print(f"z: {z_new}, z_shape: {z_new.shape}")

z: [-0.68264457  0.57735027 -1.73205081 -0.35698492], z_shape: (4,)


In [17]:
w = np.array([0.5, 0.2, 0.1, -0.3])
b = 350

prediction_row0 = np.dot(z[0], w) + b
print(f"Prediction: {prediction_row0}")

Prediction: 348.5466406702067


In [23]:
prediction_all_four = np.dot(z, w) + b
print(prediction_all_four)

[348.54664067 349.62804165 351.24579879 350.57951889]


exercise 2

In [44]:
A = np.array([[3, 8, 1, 6],
              [9, 2, 7, 4],
              [5, 5, 2, 8],
              [1, 6, 9, 3],
              [7, 4, 6, 2]])

In [45]:
print(A[3:5, 0:3])

[[1 6 9]
 [7 4 6]]


In [46]:
print(A[1:4, 2])
print(A[1:4, 2:3])
print(A[1:4, 2].shape)
# predicting before running 3, 1

[7 2 9]
[[7]
 [2]
 [9]]
(3,)


In [47]:
max_column_sum = A.sum(axis = 0).argmax()
max_column_sum

np.int64(0)

In [48]:
A[A > 6] = 0
print(A)

[[3 0 1 6]
 [0 2 0 4]
 [5 5 2 0]
 [1 6 0 3]
 [0 4 6 2]]


In [68]:
# question 5 again
c = np.array([[10],[20],[30],[40],[50]])
print(c, c.shape, end ="\n\n")
print(A, A.shape)

c + A

[[10]
 [20]
 [30]
 [40]
 [50]] (5, 1)

[[3 0 1 6]
 [0 2 0 4]
 [5 5 2 0]
 [1 6 0 3]
 [0 4 6 2]] (5, 4)


array([[13, 10, 11, 16],
       [20, 22, 20, 24],
       [35, 35, 32, 30],
       [41, 46, 40, 43],
       [50, 54, 56, 52]])

In [70]:
d = A + np.array([10, 20, 30, 40])
# prediction is A is 5, 4 and 1, 4 which mean broadcasting works, 5, 4 is final dimension 13, 20 , 31, 46 first row and continues down
print(d, d.shape)

[[13 20 31 46]
 [10 22 30 44]
 [15 25 32 40]
 [11 26 30 43]
 [10 24 36 42]] (5, 4)


In [95]:
d = A.copy()
d = d / d.sum(axis = 1, keepdims=True)
d

array([[0.3       , 0.        , 0.1       , 0.6       ],
       [0.        , 0.33333333, 0.        , 0.66666667],
       [0.41666667, 0.41666667, 0.16666667, 0.        ],
       [0.1       , 0.6       , 0.        , 0.3       ],
       [0.        , 0.33333333, 0.5       , 0.16666667]])

In [102]:
d = A.copy()
print(d)
d.sort()
d

[[3 0 1 6]
 [0 2 0 4]
 [5 5 2 0]
 [1 6 0 3]
 [0 4 6 2]]


array([[0, 1, 3, 6],
       [0, 0, 2, 4],
       [0, 2, 5, 5],
       [0, 1, 3, 6],
       [0, 2, 4, 6]])

In [107]:
d = A.copy()
d[d <= 4] = 0
d[d > 4] = 1
d.sum(axis = 1)

array([1, 0, 2, 1, 1])

In [108]:
(A > 4).sum(axis = 1)

array([1, 0, 2, 1, 1])

In [113]:
A

array([[3, 0, 1, 6],
       [0, 2, 0, 4],
       [5, 5, 2, 0],
       [1, 6, 0, 3],
       [0, 4, 6, 2]])

In [114]:
A.T

array([[3, 0, 5, 1, 0],
       [0, 2, 5, 6, 4],
       [1, 0, 2, 0, 6],
       [6, 4, 0, 3, 2]])

In [118]:
print(A.T @ A)
# a.t shape is 4x5 and a's shpae is 5 x 4 and the answer is matix as it performs matrix multiplication here, so final shape is 4x4 
# i fogot what dot product is give an example

[[35 31 13 21]
 [31 81 34 34]
 [13 34 41 18]
 [21 34 18 65]]


In [119]:
print(A)

[[3 0 1 6]
 [0 2 0 4]
 [5 5 2 0]
 [1 6 0 3]
 [0 4 6 2]]


In [125]:
d = A[[0, 2, 4],[1, 3, 0]]
print(d)

[0 0 0]
