In [1]:
import numpy as np

In [9]:
# creation and dtype
#1
a = np.array([10., 20., 30., 40.])
print(f"a: {a} | d_type: {a.dtype}")

#2
# it produces dtype of float, as everything is promoted to float if there is one float

#3
b = np.zeros((3, 4))
c = np.ones((2, 2))
d = np.full((2, 3), -1)
print(f"b: {b} \n c: {c} \n d: {d}")

#4 
e = np.arange(10, 31, 2)
print(f"e: {e}")

a: [10. 20. 30. 40.] | d_type: float64
b: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 c: [[1. 1.]
 [1. 1.]] 
 d: [[-1 -1 -1]
 [-1 -1 -1]]
e: [10 12 14 16 18 20 22 24 26 28 30]


In [21]:
# shape and ndim

#1
#shpae of the array is (2, 3, 2) and ndim is 3 (i guessed it don't know how it came)

#2
a = np.arange(1, 13)
a = a.reshape(3, -1)
print(f"a: {a}")

#3
a = np.zeros((5, 3))
row_num, column_num = a.shape
print(f"row number: {row_num} | column number: {column_num}")

a: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
row number: 5 | column number: 3


In [34]:
# indexing and slicing
a = np.arange(10)
print(a)
print(f"third element: {a[2]} | last element: {a[-1]} | element 2 to 5: {a[2: 6]} | every single step: {a[::2]}")
a =  np.arange(12).reshape(3, 4)
print(a)
second_row = a[1]
row1_column2 = a[1, 2]
print(f"Second row: {second_row}")
print(f"row1_colum2: {row1_column2}")
print(f"column3: {a[:, 2]}")

[0 1 2 3 4 5 6 7 8 9]
third element: 2 | last element: 9 | element 2 to 5: [2 3 4 5] | every single step: [0 2 4 6 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Second row: [4 5 6 7]
row1_colum2: 6
column3: [ 2  6 10]


In [45]:
# operations and broadcasting
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a+b)
print(a*b)
print(a**2)
# dot product before running 1*10+2*20+3*30 = 140
print(np.dot(a, b))

a = np.array([1, 2, 3]) + np.array([[10], [20]])
# i predict the shape as (5, 1) as since there are 2 level already so numpy will update all to 2 levels highes level
print(f"a: {a}, a.shape:{a.shape}") # i got it wrong  don't know why

print()
a = np.arange(12).reshape(3, 4)
print(a)
print(a.sum())
print(f"column1: {a[:, 0].sum()}, column2:{a[:, 1].sum()}, column3:{a[:, 2].sum()}") # is there a way to do i without mentioning each column
print(f"row1: {a[0, :].sum()}, row2: {a[1, :].sum()}, row3: {a[2, :].sum()}")

[11 22 33]
[10 40 90]
[1 4 9]
140
a: [[11 12 13]
 [21 22 23]], a.shape:(2, 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
column1: 12, column2:15, column3:18
row1: 6, row2: 22, row3: 38
